version: "2"
services:
  node: 
    image: "robnn/node:latest"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - "8001:8001"
      - "60300:60300"
    command: "npm start"
    build:
      context: ./
      dockerfile: Dockerfile
 
